name: Publish to crates.io

on:
    push:
        tags:
            - 'v*'

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            - uses: actions-rs/toolchain@v1
              with:
                profile: minimal
                toolchain: stable
                override: true

            - name: Publish
              uses: actions-rs/cargo@v1
              with:
                command: publish
                args: --token ${{ secrets.CRATES_IO_TOKEN }}
              env:
                CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
              
